package org.openremote.modeler.shared.omnilink;

public enum OmniLinkCmd {
   
   CMD_UNIT_OFF(0),
   CMD_UNIT_ON(1),
   CMD_UNIT_AREA_ALL_OFF(2),
   CMD_UNIT_AREA_ALL_ON(3),
   CMD_BUTTON(7),
   CMD_UNIT_PERCENT(9),
   CMD_UNIT_LO9_LEVEL_HIGH7(101),
   CMD_UNIT_DECREMENT_COUNTER(10),
   CMD_UNIT_INCREMENT_COUNTER(11),
   CMD_UNIT_SET_COUNTER(12),
   CMD_UNIT_LO9_RAMP_HIGH7(13),
   CMD_UNIT_LIGHTOLIER(14),
   CMD_UNIT_UPB_REQ_STATUS(15),
   CMD_UNIT_UPB_DIM_STEP_1(17),
   CMD_UNIT_UPB_DIM_STEP_2(18),
   CMD_UNIT_UPB_DIM_STEP_3(19),
   CMD_UNIT_UPB_DIM_STEP_4(20),
   CMD_UNIT_UPB_DIM_STEP_5(21),
   CMD_UNIT_UPB_DIM_STEP_6(22),
   CMD_UNIT_UPB_DIM_STEP_7(23),
   CMD_UNIT_UPB_DIM_STEP_8(24),
   CMD_UNIT_UPB_DIM_STEP_9(25),
   CMD_UNIT_UPB_BRIGHTEN_STEP_1(33),
   CMD_UNIT_UPB_BRIGHTEN_STEP_2(34),
   CMD_UNIT_UPB_BRIGHTEN_STEP_3(35),
   CMD_UNIT_UPB_BRIGHTEN_STEP_4(36),
   CMD_UNIT_UPB_BRIGHTEN_STEP_5(37),
   CMD_UNIT_UPB_BRIGHTEN_STEP_6(38),
   CMD_UNIT_UPB_BRIGHTEN_STEP_7(39),
   CMD_UNIT_UPB_BRIGHTEN_STEP_8(40),
   CMD_UNIT_UPB_BRIGHTEN_STEP_9(41),
   CMD_UNIT_UPB_LO9_BLINK_HIGH7(26),
   CMD_UNIT_UPB_STOP_BLINK(27),
   CMD_UNIT_UPB_LINK_OFF(28),
   CMD_UNIT_UPB_LINK_ON(29),
   CMD_UNIT_UPB_LINK_SET(30),
   CMD_UNIT_CENTRALITE_SCENE_OFF(42),
   CMD_UNIT_CENTRALITE_SCENE_ON(43),
   CMD_UNIT_UPB_LED_OFF(44),
   CMD_UNIT_UPB_LED_ON(45),
   CMD_UNIT_RADIORA_PHANTOM_BUTTON_OFF(46),
   CMD_UNIT_RADIORA_PHANTOM_BUTTON_ON(46),
   CMD_UNIT_LEVITON_SCENE_OFF(60),
   CMD_UNIT_LEVITON_SCENE_ON(60),
   CMD_UNIT_LEVITON_SCENE_SET(60),
   
   CMD_SECURITY_OMNI_DISARM(48),
   CMD_SECURITY_OMNI_DAY_MODE(49),
   CMD_SECURITY_OMNI_NIGHT_MODE(50),
   CMD_SECURITY_OMNI_AWAY_MODE(51),
   CMD_SECURITY_OMNI_VACATION_MODE(52),
   CMD_SECURITY_OMNI_DAY_INSTANCE_MODE(53),
   CMD_SECURITY_OMNI_NIGHT_DELAYED_MODE(54),
   CMD_SECURITY_BYPASS_ZONE(4),
   CMD_SECURITY_RESTORE_ZONE(5),
   CMD_SECURITY_RESTORE_ALL_ZONES(6),
   CMD_SECURITY_LUMINA_HOME_MODE(49),
   CMD_SECURITY_LUMINA_SLEEP_MODE(50),
   CMD_SECURITY_LUMINA_AWAY_MODE(51),
   CMD_SECURITY_LUMINA_VACATION_MODE(52),
   CMD_SECURITY_LUMINA_PARTY_MODE(53),
   CMD_SECURITY_LUMINA_SPECIAL_MODE(54), 
   
   CMD_ENERGY_SAVER_OFF(64),
   CMD_ENERGY_SAVER_ON(65),
   
   CMD_THERMO_SET_HEAT_POINTC(66),
   CMD_THERMO_SET_COOL_POINTC(67),
   CMD_THERMO_SET_HEAT_POINTF(66),
   CMD_THERMO_SET_COOL_POINTF(67),
   CMD_THERMO_SET_SYSTEM_MODE(68),
   CMD_THERMO_SET_FAN_MODE(69),
   CMD_THERMO_SET_HOLD_MODE(70),
   CMD_THERMO_RAISE_LOWER_HEAT(71),
   CMD_THERMO_RAISE_LOWER_COOL(72),
   
   
   CMD_MESSAGE_SHOW_MESSAGE_WITH_BEEP_AND_LED(80),
   CMD_MESSAGE_SHOW_MESSAGE_WITH_BEEP_OR_LED(86),
   CMD_MESSAGE_LOG_MESSAGE(81),
   CMD_MESSAGE_CLEAR_MESSAGE(82),
   CMD_MESSAGE_SAY_MESSAGE(83),
   CMD_MESSAGE_PHONE_AND_SAY_MESSAGE(84),
   CMD_MESSAGE_SEND_MESSAGE_TO_SERIAL_PORT(85),
   
   CMD_CONSOLE_ENABLE_DISABLE_BEEPER(102),
   CMD_CONSOLE_BEEP(102),
   
   CMD_AUDIO_ZONE_SET_ON(112),
   CMD_AUDIO_ZONE_SET_MUTE(112),
   CMD_AUDIO_ZONE_SET_VOLUME(113),
   CMD_AUDIO_ZONE_SET_SOURCE(114),
   CMD_AUDIO_ZONE_SELECT_KEY(115),
   
   SENSOR_UNIT_POWER,
   SENSOR_UNIT_LEVEL,
   SENSOR_UNIT_DISPLAY,
   SENSOR_THERMO_HEAT_POINTC,
   SENSOR_THERMO_HEAT_POINTF,
   SENSOR_THERMO_COOL_POINTC,
   SENSOR_THERMO_COOL_POINTF,
   SENSOR_THERMO_SYSTEM_MODE,
   SENSOR_THERMO_FAN_MODE,
   SENSOR_THERMO_HOLD_MODE,
   SENSOR_THERMO_TEMPC,
   SENSOR_THERMO_TEMPF,
   SENSOR_ZONE_STATUS_CURRENT,
   SENSOR_ZONE_STATUS_LATCHED,
   SENSOR_ZONE_STATUS_ARMING,
   SENSOR_AREA_STATUS_MODE,
   SENSOR_AREA_STATUS_ALARM,
   SENSOR_AREA_STATUS_EXIT_DELAY,
   SENSOR_AREA_STATUS_ENTRY_DELAY,
   SENSOR_AREA_EXIT_TIMER,
   SENSOR_AREA_ENTRY_TIMER,
   SENSOR_AUX_STATUS,
   SENSOR_AUX_CURRENTC,
   SENSOR_AUX_CURRENTF,
   SENSOR_AUX_LOWC,
   SENSOR_AUX_LOWF,
   SENSOR_AUX_HIGHC,
   SENSOR_AUX_HIGHF,
   SENSOR_AUDIOZONE_POWER,
   SENSOR_AUDIOZONE_SOURCE,
   SENSOR_AUDIOZONE_VOLUME,
   SENSOR_AUDIOZONE_MUTE,
   SENSOR_AUDIOZONE_TEXT,
   SENSOR_AUDIOZONE_TEXT_FIELD1,
   SENSOR_AUDIOZONE_TEXT_FIELD2,
   SENSOR_AUDIOZONE_TEXT_FIELD3,
   SENSOR_AUDIOSOURCE_TEXT,
   SENSOR_AUDIOSOURCE_TEXT_FIELD1,
   SENSOR_AUDIOSOURCE_TEXT_FIELD2,
   SENSOR_AUDIOSOURCE_TEXT_FIELD3;
   
   private int number;
   
   OmniLinkCmd(int number){
      this.number = number;
   }
   
   OmniLinkCmd(){
      this.number = -1;
   }
   
   public int getNumber() {
      return number;
   }
   
   public static OmniLinkCmd getCommand(String name) {
      for (OmniLinkCmd command : OmniLinkCmd.values())
         if(name.equals(command.toString()))
            return command;
      return null;
   }
   
   public static OmniLinkCmd getCommand(int ordinal) {
	   OmniLinkCmd [] values = OmniLinkCmd.values();
	   if(ordinal < values.length)
		   return values[ordinal];
	   else
		   return null;
   }
   
   public static String toList(){
      StringBuilder sb = new StringBuilder();
      for (OmniLinkCmd command : OmniLinkCmd.values())
         sb.append(command.toString()).append(",");
      return sb.toString();
   }
   
   public static void main(String[] args){
	   System.out.println(toList());
   }
}
