mkdir war/WEB-INF/lib
cp lib/core/apache-commons/commons-codec-1.3.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-collections-3.2.1.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-dbcp.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-io.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-lang.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-logging-1.1.jar war/WEB-INF/lib
cp lib/core/apache-commons/commons-pool.jar war/WEB-INF/lib
cp lib/core/asm/asm.jar war/WEB-INF/lib
cp lib/core/aspectjweaver/aspectjweaver.jar war/WEB-INF/lib
cp lib/core/beanlib/beanlib-3.3.0beta21c.jar war/WEB-INF/lib
cp lib/core/beanlib/beanlib-hibernate-3.3.0beta21c.jar war/WEB-INF/lib
cp lib/core/cglib/cglib-2.1.3.jar war/WEB-INF/lib
cp lib/core/cglib/cglib-nodep-2.1_3.jar war/WEB-INF/lib
cp lib/core/dom4j/dom4j-1.6.1.jar war/WEB-INF/lib
cp lib/core/felxjson/flexjson.jar war/WEB-INF/lib
cp lib/core/gilead/adapter-core-1.2.2.598.jar war/WEB-INF/lib
cp lib/core/gilead/adapter4gwt-1.2.2.598.jar war/WEB-INF/lib
cp lib/core/gwt/gwt-servlet.jar war/WEB-INF/lib
cp lib/core/gxt/gxt.jar war/WEB-INF/lib
cp lib/core/hibernate/hibernate-annotations.jar war/WEB-INF/lib
cp lib/core/hibernate/hibernate-commons-annotations.jar war/WEB-INF/lib
cp lib/core/hibernate/hibernate-util-1.2.2.598.jar war/WEB-INF/lib
cp lib/core/hibernate/hibernate3.jar war/WEB-INF/lib
cp lib/core/jboss/archive-browsing/jboss-archive-browsing.jar war/WEB-INF/lib
cp lib/core/jboss/serialization/jboss-serialization.jar war/WEB-INF/lib
cp lib/core/log4j/log4j-1.2.11.jar war/WEB-INF/lib
cp lib/core/mysql-connector/mysql-connector-java-5.0.3-bin.jar war/WEB-INF/lib
cp lib/core/spring/spring-2.0.8.jar war/WEB-INF/lib
cp lib/core/spring/spring-security-core-2.0.4.jar war/WEB-INF/lib
cp lib/core/sun/activation.jar war/WEB-INF/lib
cp lib/core/sun/ejb3-persistence.jar war/WEB-INF/lib
cp lib/core/sun/jstl.jar war/WEB-INF/lib
cp lib/core/sun/jta.jar war/WEB-INF/lib
cp lib/core/sun/standard.jar war/WEB-INF/lib
cp lib/core/trove/trove.jar war/WEB-INF/lib

